//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathwayGames.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PathwayGames.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pathway+ Games.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete session.
        /// </summary>
        internal static string ButtonDeleteSession {
            get {
                return ResourceManager.GetString("ButtonDeleteSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export results.
        /// </summary>
        internal static string ButtonExportResults {
            get {
                return ResourceManager.GetString("ButtonExportResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game data.
        /// </summary>
        internal static string ButtonGameData {
            get {
                return ResourceManager.GetString("ButtonGameData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack.
        /// </summary>
        internal static string ButtonPack {
            get {
                return ResourceManager.GetString("ButtonPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack all.
        /// </summary>
        internal static string ButtonPackAll {
            get {
                return ResourceManager.GetString("ButtonPackAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Defaults.
        /// </summary>
        internal static string ButtonResetDefaults {
            get {
                return ResourceManager.GetString("ButtonResetDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string ButtonSelect {
            get {
                return ResourceManager.GetString("ButtonSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string LabelAdmin {
            get {
                return ResourceManager.GetString("LabelAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average response time.
        /// </summary>
        internal static string LabelAverageResponseTime {
            get {
                return ResourceManager.GetString("LabelAverageResponseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank slide display time.
        /// </summary>
        internal static string LabelBlankSlideDisplayTime {
            get {
                return ResourceManager.GetString("LabelBlankSlideDisplayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank slide variation (+-).
        /// </summary>
        internal static string LabelBlankSlideVariation {
            get {
                return ResourceManager.GetString("LabelBlankSlideVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confusion Matrix.
        /// </summary>
        internal static string LabelConfusionMatrix {
            get {
                return ResourceManager.GetString("LabelConfusionMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct commision.
        /// </summary>
        internal static string LabelCorrectCommision {
            get {
                return ResourceManager.GetString("LabelCorrectCommision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct ommisions.
        /// </summary>
        internal static string LabelCorrectOmmisions {
            get {
                return ResourceManager.GetString("LabelCorrectOmmisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye Gaze Visualization.
        /// </summary>
        internal static string LabelEyeGazeVisualization {
            get {
                return ResourceManager.GetString("LabelEyeGazeVisualization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyro / Acceleration.
        /// </summary>
        internal static string LabelGyroAcceleration {
            get {
                return ResourceManager.GetString("LabelGyroAcceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height Compensation.
        /// </summary>
        internal static string LabelHeightCompensation {
            get {
                return ResourceManager.GetString("LabelHeightCompensation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learner.
        /// </summary>
        internal static string LabelLearner {
            get {
                return ResourceManager.GetString("LabelLearner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muse EEG headband.
        /// </summary>
        internal static string LabelMuseEEGheadband {
            get {
                return ResourceManager.GetString("LabelMuseEEGheadband", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No game sessions found!.
        /// </summary>
        internal static string LabelNoGameSessionsFound {
            get {
                return ResourceManager.GetString("LabelNoGameSessionsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No users found!.
        /// </summary>
        internal static string LabelNoUsersFound {
            get {
                return ResourceManager.GetString("LabelNoUsersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        internal static string LabelPoints {
            get {
                return ResourceManager.GetString("LabelPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        internal static string LabelScore {
            get {
                return ResourceManager.GetString("LabelScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen PPI.
        /// </summary>
        internal static string LabelScreenPPI {
            get {
                return ResourceManager.GetString("LabelScreenPPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string LabelSeconds {
            get {
                return ResourceManager.GetString("LabelSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEEK AX.
        /// </summary>
        internal static string LabelSeekAX {
            get {
                return ResourceManager.GetString("LabelSeekAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEEK AX WITH QUIZ.
        /// </summary>
        internal static string LabelSeekAXWithQuiz {
            get {
                return ResourceManager.GetString("LabelSeekAXWithQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEEK X.
        /// </summary>
        internal static string LabelSeekX {
            get {
                return ResourceManager.GetString("LabelSeekX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window (secs).
        /// </summary>
        internal static string LabelSensitivity {
            get {
                return ResourceManager.GetString("LabelSensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide.
        /// </summary>
        internal static string LabelSlide {
            get {
                return ResourceManager.GetString("LabelSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide count.
        /// </summary>
        internal static string LabelSlideCount {
            get {
                return ResourceManager.GetString("LabelSlideCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide display time.
        /// </summary>
        internal static string LabelSlideDisplayTime {
            get {
                return ResourceManager.GetString("LabelSlideDisplayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tolerance.
        /// </summary>
        internal static string LabelTolerance {
            get {
                return ResourceManager.GetString("LabelTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True depth camera.
        /// </summary>
        internal static string LabelTrueDepthcamera {
            get {
                return ResourceManager.GetString("LabelTrueDepthcamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TYPE AX.
        /// </summary>
        internal static string LabelTypeAX {
            get {
                return ResourceManager.GetString("LabelTypeAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TYPE X.
        /// </summary>
        internal static string LabelTypeX {
            get {
                return ResourceManager.GetString("LabelTypeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string LabelUsername {
            get {
                return ResourceManager.GetString("LabelUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User type.
        /// </summary>
        internal static string LabelUserType {
            get {
                return ResourceManager.GetString("LabelUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width Compensation.
        /// </summary>
        internal static string LabelWidthCompensation {
            get {
                return ResourceManager.GetString("LabelWidthCompensation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong commision.
        /// </summary>
        internal static string LabelWrongCommision {
            get {
                return ResourceManager.GetString("LabelWrongCommision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong ommisions.
        /// </summary>
        internal static string LabelWrongOmmisions {
            get {
                return ResourceManager.GetString("LabelWrongOmmisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter search term.
        /// </summary>
        internal static string PlaceholderEnterSearchTerm {
            get {
                return ResourceManager.GetString("PlaceholderEnterSearchTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this session data?.
        /// </summary>
        internal static string PromptDeleteSessionData {
            get {
                return ResourceManager.GetString("PromptDeleteSessionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this user.
        /// </summary>
        internal static string PromptDeleteUser {
            get {
                return ResourceManager.GetString("PromptDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to reset to default settings?.
        /// </summary>
        internal static string PromptResetDefaultSettings {
            get {
                return ResourceManager.GetString("PromptResetDefaultSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAME SETTINGS.
        /// </summary>
        internal static string SectionGameSettings {
            get {
                return ResourceManager.GetString("SectionGameSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIVE SETTINGS.
        /// </summary>
        internal static string SectionLiveSettings {
            get {
                return ResourceManager.GetString("SectionLiveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEEK GAME SETTINGS.
        /// </summary>
        internal static string SectionSeekGameSettings {
            get {
                return ResourceManager.GetString("SectionSeekGameSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SENSOR SETTINGS.
        /// </summary>
        internal static string SectionSensorSettings {
            get {
                return ResourceManager.GetString("SectionSensorSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VISUALIZATION SETTINGS.
        /// </summary>
        internal static string SectionVisualizationSettings {
            get {
                return ResourceManager.GetString("SectionVisualizationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user.
        /// </summary>
        internal static string TitleAddUser {
            get {
                return ResourceManager.GetString("TitleAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot undo this action.
        /// </summary>
        internal static string TitleCannotUndoThisAction {
            get {
                return ResourceManager.GetString("TitleCannotUndoThisAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        internal static string TitleGames {
            get {
                return ResourceManager.GetString("TitleGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating package.
        /// </summary>
        internal static string TitleGeneratingPackage {
            get {
                return ResourceManager.GetString("TitleGeneratingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating results.
        /// </summary>
        internal static string TitleGeneratingResults {
            get {
                return ResourceManager.GetString("TitleGeneratingResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string TitleLanguage {
            get {
                return ResourceManager.GetString("TitleLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live.
        /// </summary>
        internal static string TitleLive {
            get {
                return ResourceManager.GetString("TitleLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ....
        /// </summary>
        internal static string TitleLoading {
            get {
                return ResourceManager.GetString("TitleLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected user changed to {0}.
        /// </summary>
        internal static string TitleSelectedUserChangedTo {
            get {
                return ResourceManager.GetString("TitleSelectedUserChangedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Game.
        /// </summary>
        internal static string TitleSelectGame {
            get {
                return ResourceManager.GetString("TitleSelectGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session data.
        /// </summary>
        internal static string TitleSessionData {
            get {
                return ResourceManager.GetString("TitleSessionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string TitleSettings {
            get {
                return ResourceManager.GetString("TitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved.
        /// </summary>
        internal static string TitleSettingsSaved {
            get {
                return ResourceManager.GetString("TitleSettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share data.
        /// </summary>
        internal static string TitleShareData {
            get {
                return ResourceManager.GetString("TitleShareData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share results.
        /// </summary>
        internal static string TitleShareResults {
            get {
                return ResourceManager.GetString("TitleShareResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string TitleSummary {
            get {
                return ResourceManager.GetString("TitleSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test results.
        /// </summary>
        internal static string TitleTestResults {
            get {
                return ResourceManager.GetString("TitleTestResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User added.
        /// </summary>
        internal static string TitleUserAdded {
            get {
                return ResourceManager.GetString("TitleUserAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} allready selected.
        /// </summary>
        internal static string TitleUserAllreadySelected {
            get {
                return ResourceManager.GetString("TitleUserAllreadySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name cannot be empty!.
        /// </summary>
        internal static string TitleUserNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("TitleUserNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string TitleUsers {
            get {
                return ResourceManager.GetString("TitleUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete yourself..
        /// </summary>
        internal static string TitleYouCannotDeleteYourself {
            get {
                return ResourceManager.GetString("TitleYouCannotDeleteYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string UserTypeAdmin {
            get {
                return ResourceManager.GetString("UserTypeAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learner.
        /// </summary>
        internal static string UserTypeLearner {
            get {
                return ResourceManager.GetString("UserTypeLearner", resourceCulture);
            }
        }
    }
}
