// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace PathwayGamesML.Model
{
    public class ModelInput
    {
        [ColumnName("target"), LoadColumn(0)]
        public bool Target { get; set; }


        [ColumnName("org"), LoadColumn(1)]
        public string Org { get; set; }


        [ColumnName("userid"), LoadColumn(2)]
        public float Userid { get; set; }


        [ColumnName("user_name"), LoadColumn(3)]
        public string User_name { get; set; }


        [ColumnName("date"), LoadColumn(4)]
        public float Date { get; set; }


        [ColumnName("slideCount"), LoadColumn(5)]
        public float SlideCount { get; set; }


        [ColumnName("ppi"), LoadColumn(6)]
        public float Ppi { get; set; }


        [ColumnName("press_count"), LoadColumn(7)]
        public float Press_count { get; set; }


        [ColumnName("response_time"), LoadColumn(8)]
        public float Response_time { get; set; }


        [ColumnName("eye_blink"), LoadColumn(9)]
        public float Blink { get; set; }


        [ColumnName("eye_squint"), LoadColumn(10)]
        public float Squint { get; set; }


        [ColumnName("eye_gaze_inward"), LoadColumn(11)]
        public float GazeIn { get; set; }


        [ColumnName("eye_gaze_outward"), LoadColumn(12)]
        public float GazeOut { get; set; }


        [ColumnName("smile"), LoadColumn(13)]
        public float Smile { get; set; }


        [ColumnName("frown"), LoadColumn(14)]
        public float Frown { get; set; }


        [ColumnName("head_speed"), LoadColumn(15)]
        public float HeadSpeed { get; set; }


        [ColumnName("eye_dwelling"), LoadColumn(16)]
        public float EyeDwell { get; set; }


        [ColumnName("head_tilt"), LoadColumn(17)]
        public float HeadTilt { get; set; }


    }
}
