// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.IO;
using System.Linq;
using Microsoft.ML;
using PathwayGamesML.Model;

namespace PathwayGamesML.ConsoleApp
{
    class Program
    {
        //Dataset to use for predictions 
        private const string DATA_FILEPATH = @"D:\dev\projects\pathway+ml\pathway+ data\pathway_data_fixed.tsv";

        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = CreateSingleDataSample(DATA_FILEPATH);

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Target with predicted Target from sample data...\n\n");
            Console.WriteLine($"org: {sampleData.Org}");
            Console.WriteLine($"userid: {sampleData.Userid}");
            Console.WriteLine($"user_name: {sampleData.User_name}");
            Console.WriteLine($"date: {sampleData.Date}");
            Console.WriteLine($"slideCount: {sampleData.SlideCount}");
            Console.WriteLine($"ppi: {sampleData.Ppi}");
            Console.WriteLine($"press_count: {sampleData.Press_count}");
            Console.WriteLine($"response_time: {sampleData.Response_time}");
            Console.WriteLine($"eye_blink: {sampleData.Blink}");
            Console.WriteLine($"eye_squint: {sampleData.Squint}");
            Console.WriteLine($"eye_gaze_inward: {sampleData.GazeIn}");
            Console.WriteLine($"eye_gaze_outward: {sampleData.GazeOut}");
            Console.WriteLine($"smile: {sampleData.Smile}");
            Console.WriteLine($"frown: {sampleData.Frown}");
            Console.WriteLine($"head_speed: {sampleData.HeadSpeed}");
            Console.WriteLine($"eye_dwelling: {sampleData.EyeDwell}");
            Console.WriteLine($"head_tilt: {sampleData.HeadTilt}");
            Console.WriteLine($"\n\nActual Target: {sampleData.Target} \nPredicted Target: {predictionResult.Prediction}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }

        // Change this code to create your own sample data
        #region CreateSingleDataSample
        // Method to load single row of dataset to try a single prediction
        private static ModelInput CreateSingleDataSample(string dataFilePath)
        {
            // Create MLContext
            MLContext mlContext = new MLContext();

            // Load dataset
            IDataView dataView = mlContext.Data.LoadFromTextFile<ModelInput>(
                                            path: dataFilePath,
                                            hasHeader: true,
                                            separatorChar: '\t',
                                            allowQuoting: true,
                                            allowSparse: false);

            // Use first line of dataset as model input
            // You can replace this with new test data (hardcoded or from end-user application)
            ModelInput sampleForPrediction = mlContext.Data.CreateEnumerable<ModelInput>(dataView, false)
                                                                        .First();
            return sampleForPrediction;
        }
        #endregion
    }
}
